<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Deskworlds</AssemblyName>
    <RootNamespace>Deskworlds</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>deskworlds.ico</ApplicationIcon>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Version>1.1.0</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2792.45" />
    <EmbeddedResource Include="deskworlds.ico" LogicalName="deskworlds.ico" />
  </ItemGroup>

</Project>
